twig:
    default_path: '%kernel.project_dir%/templates'
    #Applique un type de form pour tous les formulaires de l'application
    form_themes: ['view/form_theme/beautiful_form.html.twig']

when@test:
    twig:
        strict_variables: true
